version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./Python/Dockerfile
    ports:
      - 5000:5000
    container_name: flask
    volumes:
      - ./Python:/Python
    tty: true
    restart: always

  java:
    build:
      context: .
      dockerfile: /Java/Dockerfile
    container_name: java
    tty: true
    volumes:
      - ./Java:/Java
    working_dir: /Java
    ports:
      - 8080:8080

  mysql:
    build: ./mysql
    container_name: mysql
    env_file:
      - ./mysql/db.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    ports:
      - 3306:3306
